[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gitviz"
version = "0.1.0"
description = "A way of visualising Git repositories through a command line"
requires-python = ">=3.9"
dependencies = [
    "PyGithub",
    "colorama",
    "python-dotenv",
]

[project.scripts]
gitviz = "main:main"

[tool.setuptools]
py-modules = ["main", "RepoData"]
packages = ["cmds", "utils"]
